-- AlterTable
ALTER TABLE `job` ADD COLUMN `recruiterId` VARCHAR(191) NULL;

-- AlterTable
ALTER TABLE `user` MODIFY `role` ENUM('USER', 'SUPER_ADMIN', 'INSTRUCTOR', 'COMMUNITY_MANAGER', 'PARTNER_MANAGER', 'RECRUITER') NOT NULL DEFAULT 'USER';

-- AddForeignKey
ALTER TABLE `Job` ADD CONSTRAINT `Job_recruiterId_fkey` FOREIGN KEY (`recruiterId`) REFERENCES `User`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;
